server:
  # 端口
  port: 8201

spring:
  # 服务名
  application:
    name: service-hosp
  # 环境配置文件
  profiles:
    active: dev
  # MySQL数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hospital_dev?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  # json全局时间格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#  # nacos 服务地址
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#    # sentinel 地址
#    sentinel:
#      transport:
#        dashboard: http://127.0.0.1:8848
#
#  # mongodb
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: hostipal_hosp
#
#  # rabbitmq
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
#
#
## mybatis-plus
#mybatis-plus:
#  mapper-locations: classpath:com/example/hospital/mapper/xml/*.xml
#
## sentinel
#feign:
#  sentinel:
#    enabled: true
